import { colors, type ColorScheme } from './colors'
import { webFontStack } from './typography'

const graphiteSteps = [950, 900, 800, 700, 600, 500, 400, 300, 200, 100, 50] as const
const signalSteps = [600, 500, 400] as const
const statusTones = ['ok', 'warn', 'danger'] as const

const rampLines = (scheme: ColorScheme): ReadonlyArray<string> => {
  const palette = colors[scheme]

  return [
    ...graphiteSteps.map((step) => `--color-graphite-${step}: ${palette.graphite[step]};`),
    '',
    ...signalSteps.map((step) => `--color-signal-${step}: ${palette.signal[step]};`),
    '',
    ...statusTones.map((tone) => `--color-status-${tone}: ${palette.status[tone]};`),
  ]
}

const indent = (lines: ReadonlyArray<string>, depth: number): string =>
  lines.map((line) => (line === '' ? '' : `${'  '.repeat(depth)}${line}`)).join('\n')

export const renderThemeCss = (): string =>
  [
    '/* Generated by scripts/generate-theme-css.ts from src/tokens. Run `pnpm generate:theme` instead of editing. */',
    '',
    '@theme {',
    indent(rampLines('dark'), 1),
    '',
    `  --font-display: ${webFontStack.display};`,
    `  --font-sans: ${webFontStack.sans};`,
    '}',
    '',
    ':root {',
    '  color-scheme: dark;',
    '}',
    '',
    "[data-theme='light'] {",
    indent(rampLines('light'), 1),
    '',
    '  color-scheme: light;',
    '}',
    '',
    '@media (prefers-color-scheme: light) {',
    "  [data-theme='system'] {",
    indent(rampLines('light'), 2),
    '',
    '    color-scheme: light;',
    '  }',
    '}',
    '',
  ].join('\n')
