export const ApiErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  USER_UNKNOWN: 'USER_UNKNOWN',
  ADMIN_SELF_LOCKOUT: 'ADMIN_SELF_LOCKOUT',
  PREFERRED_ATELIER_NOT_JOINED: 'PREFERRED_ATELIER_NOT_JOINED',

  ATELIER_NOT_FOUND: 'ATELIER_NOT_FOUND',
  ATELIER_UNKNOWN: 'ATELIER_UNKNOWN',
  ATELIER_SLUG_TAKEN: 'ATELIER_SLUG_TAKEN',
  ATELIER_NOT_JOINABLE: 'ATELIER_NOT_JOINABLE',
  MEMBERSHIP_UNKNOWN: 'MEMBERSHIP_UNKNOWN',

  MACHINE_UNKNOWN: 'MACHINE_UNKNOWN',

  MACHINE_NOT_CERTIFIABLE: 'MACHINE_NOT_CERTIFIABLE',
  CERTIFICATION_ALREADY_REQUESTED: 'CERTIFICATION_ALREADY_REQUESTED',
  CERTIFICATION_UNKNOWN: 'CERTIFICATION_UNKNOWN',

  MACHINE_NOT_BOOKABLE: 'MACHINE_NOT_BOOKABLE',
  MACHINE_UNAVAILABLE: 'MACHINE_UNAVAILABLE',
  MISSING_CERTIFICATION: 'MISSING_CERTIFICATION',
  SLOT_IN_THE_PAST: 'SLOT_IN_THE_PAST',
  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  BOOKING_UNKNOWN: 'BOOKING_UNKNOWN',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_NOT_CHECK_INABLE: 'BOOKING_NOT_CHECK_INABLE',
  CHECK_IN_WINDOW_CLOSED: 'CHECK_IN_WINDOW_CLOSED',
  BOOKING_NOT_MARKABLE_AS_NO_SHOW: 'BOOKING_NOT_MARKABLE_AS_NO_SHOW',
  CHECK_IN_TOKEN_MISMATCH: 'CHECK_IN_TOKEN_MISMATCH',
} as const

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode]
